# ChemSim configuration template (draft)
#
# TODO: Replace placeholder values with scenario-specific data.

metadata:
  name: "placeholder_scenario"
  description: "Prototype configuration to validate schema."
  version: "0.0.1-draft"
  authors: ["TODO"]

simulation:
  timestep_fs: 1.0
  total_steps: 1000
  integrator: "velocity_verlet"
  neighbor_list:
    type: "cell"
    update_frequency: 10
  boundary_conditions:
    type: "periodic"
    box_lengths_angstrom: [30.0, 30.0, 30.0]

thermostat:
  enabled: false
  type: "nose_hoover"
  target_temperature_k: 300.0
  relaxation_time_fs: 100.0

force_fields:
  families:
    - name: "placeholder"
      description: "Lennard-Jones prototype."
  parameters_file: "data/potentials/example_lj.csv"

system:
  atoms:
    - id: 1
      element: "H"
      position_angstrom: [0.0, 0.0, 0.0]
      velocity_angstrom_fs: [0.0, 0.0, 0.0]
    - id: 2
      element: "H"
      position_angstrom: [0.74, 0.0, 0.0]
      velocity_angstrom_fs: [0.0, 0.0, 0.0]

environment:
  em_field:
    enabled: false
    electric_field_v_nm: [0.0, 0.0, 0.0]
    magnetic_field_t: [0.0, 0.0, 0.0]
  photon_source:
    enabled: false
    wavelength_nm: null
    intensity_w_cm2: null

output:
  trajectory_interval: 50
  energy_interval: 10
  diagnostics_interval: 100
  export:
    directory: "output/placeholder"
    formats: ["jsonl"]

ui:
  camera:
    focus: [0.0, 0.0, 0.0]
    zoom: 1.0
  panels:
    periodic_table_visible: true
    inspector_visible: false
  theme: "dark"
