metadata:
  name: "Argon Cloud"
  description: "Sparse argon atoms to showcase gas expansion/repulsion."

simulation:
  timestep_fs: 1.0
  periodic: false
  target_temperature_k: 400
  thermostat_tau_fs: 80

force_fields:
  pairs:
    - element_i: Ar
      element_j: Ar
      epsilon_kj_mol: 0.995
      sigma_angstrom: 3.4

system:
  atoms:
    - id: 1
      element: Ar
      mass_amu: 39.948
      position_angstrom: [0.0, 0.0, 0.0]
      phase: gas
    - id: 2
      element: Ar
      mass_amu: 39.948
      position_angstrom: [4.0, 2.0, 0.0]
      phase: gas
    - id: 3
      element: Ar
      mass_amu: 39.948
      position_angstrom: [-3.5, -1.5, 0.0]
      phase: gas
    - id: 4
      element: Ar
      mass_amu: 39.948
      position_angstrom: [1.5, -3.0, 0.0]
      phase: gas
    - id: 5
      element: Ar
      mass_amu: 39.948
      position_angstrom: [-2.5, 3.0, 0.0]
      phase: gas
