metadata:
  name: "Water Cluster"
  description: "Three-water cluster held in space to show hydrogen bonding."

simulation:
  timestep_fs: 0.5
  periodic: false
  target_temperature_k: 320
  thermostat_tau_fs: 50

force_fields:
  pairs:
    - element_i: H
      element_j: H
      epsilon_kj_mol: 0.1
      sigma_angstrom: 2.5
    - element_i: H
      element_j: O
      epsilon_kj_mol: 0.16
      sigma_angstrom: 3.0
    - element_i: O
      element_j: O
      epsilon_kj_mol: 0.21
      sigma_angstrom: 3.3
  bonds:
    - element_i: H
      element_j: O
      k_kj_mol_nm2: 450
      r0_angstrom: 0.97
  angles:
    - element_i: H
      element_j: O
      element_k: H
      k_kj_mol_rad2: 60
      theta0_degrees: 104.5

system:
  atoms:
    - id: 1
      element: O
      mass_amu: 15.999
      position_angstrom: [0.0, 0.0, 0.0]
      phase: liquid
    - id: 2
      element: H
      mass_amu: 1.008
      position_angstrom: [0.95, 0.3, 0.0]
      phase: liquid
    - id: 3
      element: H
      mass_amu: 1.008
      position_angstrom: [-0.95, 0.3, 0.0]
      phase: liquid
    - id: 4
      element: O
      mass_amu: 15.999
      position_angstrom: [2.8, 0.0, 0.0]
      phase: liquid
    - id: 5
      element: H
      mass_amu: 1.008
      position_angstrom: [3.7, 0.3, 0.0]
      phase: liquid
    - id: 6
      element: H
      mass_amu: 1.008
      position_angstrom: [2.0, 0.4, 0.0]
      phase: liquid
    - id: 7
      element: O
      mass_amu: 15.999
      position_angstrom: [-3.0, 0.2, 0.0]
      phase: liquid
    - id: 8
      element: H
      mass_amu: 1.008
      position_angstrom: [-3.9, 0.5, 0.0]
      phase: liquid
    - id: 9
      element: H
      mass_amu: 1.008
      position_angstrom: [-2.1, 0.6, 0.0]
      phase: liquid
